version: "3.8"

services:
  server:
    container_name: server
    build:
      context: .
    stdin_open: true
    tty: true
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    env_file:
      - .env.dev
    command: >
      sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    env_file:
      - .env.dev

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
