from .get_menu import GetMenu
from .create_order import CreateOrder
from .update_order import UpdateOrder
from .add_items import AddItems
from .find_orders import FindOrders
from .update_item import UpdateItem
from .remove_item import RemoveItem
from .get_discounts import GetDiscount
from .apply_discount import ApplyDiscount
from .get_order_by_type import GetOrderByType
from .create_rentalbooking import CreateRentalBooking
from .create_ride import CreateRide
from .set_status_rental import SetStatusRental
from .set_status_ride import SetStatusRide
from .find_all_riderequests import GetAllRides
from .find_all_rentalbookings import GetAllRentalBookings
from .find_all_rentals import GetAllRentals