FROM python:3.10.5
ENV PYTHONUNBUFFERED 1
ENV DJANGO_ENV=development
# Create app directory
WORKDIR /app

# Create Python virtualenv and use it
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY ./dev_requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r dev_requirements.txt 


COPY . /app
