# Generated by Django 4.0.4 on 2023-09-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
