# Generated by Django 4.0.4 on 2023-09-03 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_delete_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('percent', models.FloatField(default=0)),
                ('upto', models.FloatField(default=0)),
                ('min_price', models.FloatField(default=0)),
                ('linked_to', models.PositiveSmallIntegerField(choices=[(1, 'Location'), (2, 'Item'), (3, 'Provider')], default=2)),
                ('to_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.fooditem')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.location')),
                ('to_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.provider')),
            ],
        ),
    ]
