# Generated by Django 4.0.4 on 2023-09-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userinfo_room'),
        ('gig', '0001_initial'),
        ('service', '0006_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='rental')),
                ('engineCapacity', models.CharField(max_length=255)),
                ('mileage', models.CharField(max_length=255)),
                ('fuelType', models.CharField(max_length=255)),
                ('seatingCapacity', models.IntegerField()),
                ('_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userinfo'),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_coordinates', models.CharField(max_length=255)),
                ('end_coordinates', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Completed'), (3, 'Cancelled'), (4, 'Rejected')], default=0)),
                ('distance', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('commission', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.worker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_coordinates', models.CharField(max_length=255)),
                ('end_coordinates', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Completed'), (3, 'Cancelled'), (4, 'Rejected')], default=0)),
                ('distance', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('commission', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.rental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
        ),
    ]
