# Generated by Django 4.0.4 on 2023-09-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rental_alter_order_user_ride_rentalbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='provider',
        ),
    ]
