# Generated by Django 4.0.4 on 2023-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_rename_amount_ride_price_remove_rentalbooking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='engineCapacity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='fuelType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.ImageField(null=True, upload_to='rental'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='mileage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='seatingCapacity',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
