# Generated by Django 4.0.4 on 2023-09-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_rental__type_alter_rental_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
