# Generated by Django 4.0.4 on 2023-10-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rental',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
