"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-at)hxvzc$-n-u*=+5jp0)pbwkzp40=pwomctbrp^iw$wm%m!#=')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# Add subdomain hostname of client app here
ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://brisphere-django-backend.agreeablebush-b77b4bbe.southeastasia.azurecontainerapps.io','https://64d350c97ae58a40cd671c31--nestafar.netlify.app']
DEBUG = False
DEBUG_PROPAGATE_EXCEPTIONS = True

# SECURITY WARNING: keep the secret key used in production secret!
# Use this py command to create secret 
# python -c 'import secrets; print(secrets.token_hex())'
SECRET_KEY = os.getenv('AZURE_SECRET_KEY','d6803b0530e96ef9ec410ae0a7f7d5671c1228288a5b112f3b20f64219d5ab62')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

CORS_ALLOWED_ORIGINS = [
   '*'
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cabin.apps.CabinConfig',
    'service.apps.ServiceConfig',
    'user.apps.UserConfig',
    'package.apps.PackageConfig',
    'gig.apps.GigConfig',
    'rest_framework',
    'sslserver',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # 'django.middleware.cache.UpdateCacheMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': os.environ.get('MYSQL_DATABASE', 'backenddb'),
#         'USER': os.environ.get('MYSQL_USER', 'root'),
#         'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'wrench123'),
#         'HOST': os.environ.get('MYSQL_DATABASE_HOST', 'db'),
#         'PORT': os.environ.get('MYSQL_DATABASE_PORT', 3306),
#     }
# }

DATABASES = {
    'default': {
         'ENGINE': 'mssql',
         'NAME': os.environ.get('MYSQL_DATABASE', 'backenddb'),
         'USER': os.environ.get('MYSQL_USER', 'brisphere'),
         'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'Wrench@123'),
         'HOST':  os.environ.get('MYSQL_DATABASE_HOST', 'brispheresql.database.windows.net'),
         'OPTIONS': { 
             'driver': 'ODBC Driver 18 for SQL Server', 
               }
     }
}
USE_TZ = False

# Caches
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FAST2SMS_API_KEY = 'img7wq1H3ouRd2SjMnzkGsX4cUl6CfQYEADBebOIxP5F9LahtJDcVWZT2ERv9B7C3YAaHobt51G0pwKe'
FAST2SMS_API_ENDPOINT = 'https://www.fast2sms.com/dev/bulkV2'
