# Generated by Django 4.0.4 on 2023-09-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='room',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
