# Generated by Django 4.0.4 on 2023-09-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userinfo_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='otp',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='property_id',
            field=models.IntegerField(null=True),
        ),
    ]
