# Generated by Django 4.0.4 on 2023-10-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0003_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmetadata',
            name='airquality',
            field=models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=5),
        ),
    ]
