# Generated by Django 4.0.4 on 2023-10-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0004_alter_locationmetadata_airquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(default='king', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.TextField(default='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='nice room', max_length=100),
            preserve_default=False,
        ),
    ]
