# Generated by Django 4.0.4 on 2023-10-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userinfo_otp_userinfo_property_id'),
        ('cabin', '0006_property_directions_room_occuptancy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rooms',
            new_name='roomsbooked',
        ),
        migrations.AddField(
            model_name='property',
            name='tag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Family'), (2, 'Adventure'), (3, 'Lavish')], default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='cabin.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='user.userinfo'),
        ),
    ]
