# Generated by Django 4.0.4 on 2023-09-06 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0021_alter_paymentstatus_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 16, 24, 52, 132479)),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 16, 24, 52, 132493)),
        ),
    ]
